### ISSUE TITLE
Issue regarding installation of Hbind

### ISSUE THREAD

**Issue by rohityadav901** [rasbt/Hbind#1]
Hi Sir, 

I tried installing Hbind for a better understanding the interactive residues between protein and ligands, but faced an issue regarding installation, i have already installed all the dependencies required for your tool, but when i run perl install_hbind.pl it does run the installation but after completion, it creates a empty **/bin** subdirectory.

**Comment by rasbt** [comment]
Hi there,

hm, this is weird. I just tried it and it worked for me. When you run 

    perl install_hbind.pl

the last few lines of the output of this command should look like this:


```

*** compiling interactions auxiliaries ***

make: `../../bin/hbind' is up to date.

*** compiling template auxiliaries ***

make: `../../bin/hbind' is up to date.

*** HBIND installation completed ***


*** Please see license.txt for licensing and use information ***
```

was that true in your case? Or did it throw any errors?

**Comment by rohityadav901** [comment]
After installation, the last few lines showed error like this 

`GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
Compiler executable checksum: fa57db1fe2d756b22d454aa8428fd3bd
eigen.c: In function ‘eigen’:
eigen.c:197:29: error: ‘HUGE’ undeclared (first use in this function); did you mean ‘HG’?
   tred2 ( a, b, c, e, 1.0 / HUGE );
                             ^~~~
                             HG
eigen.c:197:29: note: each undeclared identifier is reported only once for each function it appears in
Makefile:84: recipe for target 'eigen.o' failed
make: *** [eigen.o] Error 1

*** HBIND installation completed ***


*** Please see license.txt for licensing and use information ***

`

Mostly it showed error related to `eigen.c:197:29: error: ‘HUGE’ undeclared (first use in this function); did you mean ‘HG’?
   tred2 ( a, b, c, e, 1.0 / HUGE );`

**Comment by rasbt** [comment]
For some reason my compiler doesn't complain about, but it's correct that it's not defined. Could you try changing HUGE to HG in 

    Hbind-master/src/hbind/eigen.c

to see if that fixes the issue?

**Comment by rohityadav901** [comment]
Hi Sebastian, 

It's working now after changing HUGE to HG. 

Thanks for your support.

**Comment by rasbt** [comment]
Glad to hear that it solved the issue. I will update the code here too to make sure that others won't bump into the same problem.
